name: archtech
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  

  
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  freezed: ^3.2.3
  flutter_bloc: ^9.1.1
  build_runner: ^2.10.5
  shared_preferences: ^2.5.3
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  equatable: ^2.0.8
  json_serializable: ^6.11.2

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/signin/
    - assets/images/forgot_password/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-SemiBold.ttf

